# Generated by Django 4.2 on 2023-04-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('id_image', models.ImageField(null=True, upload_to='id_images/')),
                ('extracted_id_image', models.ImageField(null=True, upload_to='extracted_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='live_images/')),
                ('is_face_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recognition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.recognition')),
            ],
        ),
    ]
